import type { TokenMap } from './types'

/**
 * Legacy token bridge — all values route through unified surface system.
 */
export function computeLegacyTokens(_primitives: TokenMap): TokenMap {
  return {
    '--shell-bg': 'var(--gc-surface-base)',
    '--shell-bg-elevated': 'var(--gc-surface-elevated)',
    '--shell-bg-hover': 'var(--gc-surface-elevated)',
    '--shell-text': 'var(--gc-text)',
    '--shell-text-secondary': 'var(--gc-text-muted)',
    '--shell-text-tertiary': 'var(--gc-text-muted)',
    '--shell-border': 'var(--gc-border)',
    '--shell-border-light': 'var(--gc-border-subtle)',
    '--shell-active': 'var(--gc-accent)',
    '--text': 'var(--gc-text)',
    '--text-muted': 'var(--gc-text-muted)',
    '--accent': 'var(--gc-accent)',
    '--accent-hover': 'var(--gc-accent-hover)',
    '--accent-light': 'var(--gc-accent-bg)',
    '--border': 'var(--gc-border)',
    '--border-hover': 'var(--gc-border-strong)',
    '--border-glow': 'var(--gc-accent-bg)',
    '--bg-card': 'var(--gc-surface-elevated)',
    '--bg-input': 'var(--gc-surface-base)',
    '--bg-sidebar': 'var(--gc-surface-elevated)',
    '--bg-glass': 'var(--gc-surface-elevated)',
    '--bg-glass-light': 'var(--gc-surface-base)',
    '--surface-panel': 'var(--gc-surface-elevated)',
    '--surface-panel-strong': 'var(--gc-surface-elevated)',
    '--surface-panel-soft': 'var(--gc-surface-base)',
    '--surface-panel-soft-strong': 'var(--gc-surface-elevated)',
    '--surface-panel-muted': 'var(--gc-surface-base)',
    '--surface-panel-muted-strong': 'var(--gc-surface-elevated)',
    '--surface-panel-hover': 'var(--gc-surface-elevated)',
    '--surface-panel-hover-soft': 'var(--gc-surface-elevated)',
    '--surface-panel-hover-faint': 'var(--gc-surface-base)',
    '--surface-subtle': 'var(--gc-surface-base)',
    '--surface-subtle-strong': 'var(--gc-surface-elevated)',
    '--surface-overlay': 'var(--gc-surface-overlay)',
    '--surface-overlay-strong': 'var(--gc-surface-overlay)',
    '--surface-code': 'var(--gc-surface-base)',
    '--surface-card-gradient': 'var(--gc-surface-elevated)',
    '--surface-hero-gradient': 'var(--gc-surface-elevated)',
    '--surface-sidebar-gradient': 'var(--gc-surface-elevated)',
    '--focus-ring': 'var(--gc-accent-bg)',
    '--shadow': 'var(--gc-shadow)',
    '--shadow-sm': 'var(--gc-shadow-sm)',
    '--glass-blur': 'var(--gc-blur)',
    '--glass-reflection': 'var(--gc-surface-elevated)',
    '--header-gradient': 'var(--gc-surface-elevated)',
  }
}
